[package]
name = "neoshell"
version = "0.1.0"
authors = ["Nils 'Linkie Pi' Reid <nils.reid@neoshadow.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.6.2"
failure = "0.1.7"
